name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y
          libncurses-dev
          libssl-dev
          protobuf-compiler
          libprotobuf-dev
          cmake
          build-essential

      - name: Configure
        run: cmake -B build
          -DBUILD_EXAMPLES=ON
          -DUSE_CRYPTO=OpenSSL

      - name: Build
        run: cmake --build build

      - name: Check binary exists
        run: test -f build/bin/hashed2nite
